# Generated by Django 4.0.2 on 2022-05-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='value',
            field=models.CharField(max_length=100),
        ),
    ]
