# Generated by Django 3.2 on 2022-06-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_room_alter_message_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='value',
            field=models.CharField(max_length=10000),
        ),
    ]
